-- ============================================================
-- PPE STOCK · Migration: signatures + rcvSeq
-- ใช้กับ Supabase ที่สร้างจาก schema.sql ไว้แล้ว
-- วิธีใช้: Supabase Dashboard → SQL Editor → New query → paste → Run
-- ============================================================

-- ---------- ตารางลายเซ็นผู้รับของ ----------
-- เก็บลายเซ็น (PNG base64) ของแต่ละใบเบิก อ้างอิงด้วยเลขที่ใบเบิก (ref)
create table if not exists signatures (
  id          bigint generated by default as identity primary key,
  ref         text not null,
  party       text,
  date_text   text,
  data        text not null,            -- data:image/png;base64,...
  created_at  timestamptz default now()
);
create index if not exists signatures_ref_idx on signatures(ref);

-- ---------- running number ของใบรับเข้า (RCV) ----------
-- เริ่มที่ 40 เพื่อให้ใบถัดไปเป็น RCV-0041 (ต่อจาก seed เดิม)
insert into app_meta(k,v) values ('rcvSeq', 40) on conflict (k) do nothing;

-- ---------- ROW LEVEL SECURITY ----------
alter table signatures enable row level security;

-- เขียนได้เฉพาะผู้ login (จนท.คลัง), อ่านได้สาธารณะ (เหมือนตารางอื่น)
drop policy if exists "auth_all"    on signatures;
create policy "auth_all"    on signatures for all    to authenticated using (true) with check (true);
drop policy if exists "public_read" on signatures;
create policy "public_read" on signatures for select to anon using (true);
